# RESTful Client 测试文件
@baseUrl = http://snail.local

## 普通请求
### -----------------------------
GET  {{baseUrl}}/about HTTP/1.1
###
POST  {{baseUrl}}/about HTTP/1.1
### -----------------------------
GET {{baseUrl}}/welcome HTTP/1.1
###
POST {{baseUrl}}/welcome HTTP/1.1
### -----------------------------
POST {{baseUrl}}/submit HTTP/1.1
Content-Type: application/x-www-form-urlencoded

name=foo&password=bar

## API 测试
### ----------------------------
GET {{baseUrl}}/api/users HTTP/1.1
